"""
╔═══════════════════════════════════════════════════════════════════════════════╗
║  DataScience Flow v9.5 — Jupyter Notebook (.ipynb) Generator                ║
║  Generates comprehensive, well-structured notebooks from user operations    ║
║  Part of HMG Academy Ecosystem — Subsidiary of HMG Concepts                ║
╚═══════════════════════════════════════════════════════════════════════════════╝
"""
import json
import pandas as pd
import numpy as np
from datetime import datetime


def _md_cell(source: str) -> dict:
    """Create a Markdown cell."""
    if isinstance(source, str):
        source = [line + "\n" for line in source.split("\n")]
        source[-1] = source[-1].rstrip("\n")
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": source
    }


def _code_cell(source: str, outputs=None, cell_id=None) -> dict:
    """Create a Code cell."""
    if isinstance(source, str):
        source = [line + "\n" for line in source.split("\n")]
        source[-1] = source[-1].rstrip("\n")
    cell = {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": outputs or [],
        "source": source
    }
    if cell_id:
        cell["id"] = cell_id
    return cell


def generate_full_notebook(df_info: dict, operations: list, options: dict = None) -> str:
    """
    Generate a comprehensive Jupyter notebook from user operations.

    Args:
        df_info: Dict with dataset info (filename, rows, cols, etc.)
        operations: List of operation dicts from audit log
        options: Customization options (include_eda, include_ml, etc.)

    Returns:
        JSON string of the .ipynb file
    """
    options = options or {}
    include_eda = options.get("include_eda", True)
    include_cleaning = options.get("include_cleaning", True)
    include_stats = options.get("include_stats", True)
    include_ml = options.get("include_ml", True)
    include_visualisation = options.get("include_visualisation", True)
    include_deployment = options.get("include_deployment", True)
    dataset_name = df_info.get("filename", "dataset")
    rows = df_info.get("rows", 0)
    cols = df_info.get("cols", 0)

    cells = []

    # ═══════════════ TITLE & INTRODUCTION ═══════════════
    cells.append(_md_cell(f"""# 🔬 DataScience Flow — Complete Analysis Notebook

**Generated by:** DataScience Flow v9.5 | HMG Academy — Subsidiary of HMG Concepts

**Dataset:** {dataset_name} ({rows:,} rows × {cols} columns)

**Generated on:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

**Builder:** Adewale Samson Adeagbo | Founder, HMG Concepts (est. 2015)

---

> This notebook was auto-generated by **DataScience Flow** — the 50+ module enterprise data science
> workflow platform built by **HMG Academy** (a subsidiary of **HMG Concepts**).
> Every stage of the data science lifecycle is covered: Collection → Cleaning → EDA → Engineering → ML → Deployment.
>
> 🔗 [Portfolio](https://cssadewale.pages.dev/) | [HMG Concepts](https://hmgconcepts.pages.dev/) | [HMG Academy](https://hmgacademy.pages.dev/) | [HMG Technologies](https://hmgtechnologies.pages.dev/) | [HMG Media](https://hmgmedia.pages.dev/) | [HMG Gospel](https://hmggospel.pages.dev/)

---

## 📋 Table of Contents
1. Setup & Data Loading
2. Data Exploration & Profiling
3. Data Cleaning & Preprocessing
4. Statistical Analysis
5. Visualisation & EDA
6. Feature Engineering
7. Machine Learning Pipeline
8. Model Evaluation & Explainability
9. Export & Deployment

---
"""))

    # ═══════════════ SECTION 1: SETUP ═══════════════
    cells.append(_md_cell("## 1. Setup & Data Loading\n\nImport libraries and load the dataset."))
    cells.append(_code_cell("""# ═══════════════════════════════════════════════════════════
# DataScience Flow v9.5 — Generated Analysis Notebook
# Part of HMG Academy Ecosystem — Subsidiary of HMG Concepts
# Built by Adewale Samson Adeagbo
# ═══════════════════════════════════════════════════════════

# Core libraries
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Visualisation
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

# Statistics
from scipy import stats
import statsmodels.api as sm

# Machine Learning
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder, MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.metrics import (
    accuracy_score, classification_report, confusion_matrix,
    roc_auc_score, roc_curve, mean_squared_error, r2_score
)

# Display settings
pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 100)
pd.set_option('display.float_format', '{:.4f}'.format)

print("✅ All libraries imported successfully!")
print(f"📊 Pandas version: {pd.__version__}")
print(f"🔢 NumPy version: {np.__version__}")
"""))

    cells.append(_code_cell(f"""# Load the dataset
# Replace 'your_file.csv' with your actual file path
df = pd.read_csv('your_file.csv')

print(f"Dataset shape: {{df.shape[0]:,}} rows × {{df.shape[1]}} columns")
print(f"Memory usage: {{df.memory_usage(deep=True).sum() / 1024 / 1024:.1f}} MB")
df.head()
"""))

    # ═══════════════ SECTION 2: DATA EXPLORATION ═══════════════
    if include_eda:
        cells.append(_md_cell("""## 2. Data Exploration & Profiling

**What is EDA?** Exploratory Data Analysis is the critical first step after loading data. 
It answers fundamental questions:
- What does the data look like?
- Are there missing values or duplicates?
- What are the data types and distributions?
- Are there unexpected anomalies?

### Key Concepts
| Concept | What to Check | Why It Matters |
|---------|--------------|----------------|
| Shape | Rows × Columns | Dataset size determines approach |
| Data Types | Numeric vs Categorical | Determines valid operations |
| Missing Values | Null/NaN counts | Can break models and bias results |
| Duplicates | Repeated rows | Inflates statistics |
| Distributions | Skewness, outliers | Guides transformations |
"""))

        cells.append(_code_cell("""# ═══════════════ Dataset Overview ═══════════════
print("=" * 60)
print("DATASET OVERVIEW")
print("=" * 60)

# Basic info
print(f"\\n📋 Shape: {df.shape[0]:,} rows × {df.shape[1]} columns")
print(f"📐 Duplicate rows: {df.duplicated().sum():,} ({df.duplicated().sum()/len(df)*100:.1f}%)")
print(f"🕳️ Total missing cells: {df.isnull().sum().sum():,} ({df.isnull().sum().sum()/(df.shape[0]*df.shape[1])*100:.1f}%)")

# Column types
print(f"\\n🔢 Numeric columns: {len(df.select_dtypes(include=[np.number]).columns)}")
print(f"🔤 Categorical columns: {len(df.select_dtypes(include=['object', 'string', 'category']).columns)}")
print(f"📅 Datetime columns: {len(df.select_dtypes(include=['datetime']).columns)}")

# Quick preview
print("\\n--- First 5 Rows ---")
df.head()
"""))

        cells.append(_code_cell("""# ═══════════════ Data Types & Missing Values ═══════════════
# Column-level analysis
col_info = pd.DataFrame({
    'Column': df.columns,
    'Type': df.dtypes.values,
    'Non-Null': df.notna().sum().values,
    'Null %': (df.isna().mean() * 100).round(1).values,
    'Unique': df.nunique().values,
})

# Identify potential issues
col_info['Issue'] = ''
col_info.loc[col_info['Null %'] > 50, 'Issue'] = '⚠️ >50% missing'
col_info.loc[col_info['Unique'] == len(df), 'Issue'] = '🆔 Possible ID'
col_info.loc[col_info['Unique'] == 1, 'Issue'] = '⚠️ Constant value'

print("Column Information:")
col_info
"""))

        cells.append(_code_cell("""# ═══════════════ Descriptive Statistics ═══════════════
# Numeric statistics
print("📊 Numeric Column Statistics:")
display(df.describe().round(3))

# Categorical statistics
cat_cols = df.select_dtypes(include=['object', 'string', 'category']).columns
if len(cat_cols) > 0:
    print("\\n🔤 Categorical Column Statistics:")
    display(df[cat_cols].describe())
"""))

    # ═══════════════ SECTION 3: DATA CLEANING ═══════════════
    if include_cleaning:
        cells.append(_md_cell("""## 3. Data Cleaning & Preprocessing

**Why Clean Data?** The quality of your data determines the quality of your analysis.
Every minute spent cleaning saves hours of debugging later.

### Cleaning Checklist
- [ ] Handle missing values
- [ ] Remove or flag duplicates
- [ ] Detect and handle outliers
- [ ] Fix data type inconsistencies
- [ ] Validate data ranges
"""))

        cells.append(_code_cell("""# ═══════════════ Missing Values Analysis ═══════════════
# Detailed missing values report
missing_report = pd.DataFrame({
    'Column': df.columns,
    'Missing Count': df.isnull().sum().values,
    'Missing %': (df.isnull().mean() * 100).round(2).values,
}).sort_values('Missing %', ascending=False)

missing_cols = missing_report[missing_report['Missing Count'] > 0]
if len(missing_cols) > 0:
    print(f"🕳️ {len(missing_cols)} columns have missing values:")
    display(missing_cols)
else:
    print("✅ No missing values found!")

# Visualisation
if len(missing_cols) > 0:
    fig = px.bar(missing_cols, x='Column', y='Missing %',
                title='Missing Values by Column',
                color='Missing %', color_continuous_scale='Reds')
    fig.show()
"""))

        cells.append(_code_cell("""# ═══════════════ Handle Missing Values ═══════════════
# Create a cleaned copy
df_cleaned = df.copy()

# Strategy 1: Drop columns with >50% missing
high_missing = df.columns[df.isnull().mean() > 0.5].tolist()
if high_missing:
    print(f"🗑️ Dropping {len(high_missing)} columns with >50% missing: {high_missing}")
    df_cleaned = df_cleaned.drop(columns=high_missing)

# Strategy 2: Impute numeric columns with median (robust to outliers)
num_cols = df_cleaned.select_dtypes(include=[np.number]).columns
for col in num_cols:
    if df_cleaned[col].isnull().any():
        median_val = df_cleaned[col].median()
        df_cleaned[col] = df_cleaned[col].fillna(median_val)
        print(f"   📊 {col}: Filled {df[col].isnull().sum()} nulls with median ({median_val:.2f})")

# Strategy 3: Impute categorical columns with mode
cat_cols = df_cleaned.select_dtypes(include=['object', 'string', 'category']).columns
for col in cat_cols:
    if df_cleaned[col].isnull().any():
        mode_val = df_cleaned[col].mode()[0] if len(df_cleaned[col].mode()) > 0 else 'Unknown'
        df_cleaned[col] = df_cleaned[col].fillna(mode_val)
        print(f"   🔤 {col}: Filled {df[col].isnull().sum()} nulls with mode ({mode_val})")

print(f"\\n✅ Missing values after cleaning: {df_cleaned.isnull().sum().sum()}")
"""))

        cells.append(_code_cell("""# ═══════════════ Handle Duplicates ═══════════════
dup_count = df_cleaned.duplicated().sum()
print(f"♻️ Duplicate rows: {dup_count} ({dup_count/len(df_cleaned)*100:.2f}%)")

if dup_count > 0:
    df_cleaned = df_cleaned.drop_duplicates(keep='first')
    print(f"✅ Removed {dup_count} duplicates. New shape: {df_cleaned.shape}")
else:
    print("✅ No duplicates found.")
"""))

        cells.append(_code_cell("""# ═══════════════ Outlier Detection (IQR Method) ═══════════════
print("🎯 Outlier Detection using IQR Method:")
print("-" * 50)

outlier_summary = []
num_cols = df_cleaned.select_dtypes(include=[np.number]).columns

for col in num_cols:
    Q1 = df_cleaned[col].quantile(0.25)
    Q3 = df_cleaned[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    outliers = ((df_cleaned[col] < lower) | (df_cleaned[col] > upper)).sum()
    outlier_summary.append({
        'Column': col,
        'Outliers': outliers,
        'Outlier %': f"{outliers/len(df_cleaned)*100:.1f}%",
        'Lower Bound': round(lower, 4),
        'Upper Bound': round(upper, 4),
    })

outlier_df = pd.DataFrame(outlier_summary).sort_values('Outliers', ascending=False)
outlier_df = outlier_df[outlier_df['Outliers'] > 0]
if len(outlier_df) > 0:
    display(outlier_df)
else:
    print("✅ No significant outliers detected.")
"""))

    # ═══════════════ SECTION 4: STATISTICAL ANALYSIS ═══════════════
    if include_stats:
        cells.append(_md_cell("""## 4. Statistical Analysis

### Key Concepts
| Test | When to Use | What It Tests |
|------|------------|---------------|
| T-test | Compare 2 group means | Is the difference significant? |
| Chi-square | Categorical association | Are categories independent? |
| ANOVA | Compare 3+ group means | Is any group different? |
| Correlation | Numeric association | How strongly related? |
"""))

        cells.append(_code_cell("""# ═══════════════ Correlation Analysis ═══════════════
num_cols = df_cleaned.select_dtypes(include=[np.number]).columns

if len(num_cols) >= 2:
    # Pearson correlation
    corr = df_cleaned[num_cols].corr(method='pearson')

    fig = px.imshow(corr, text_auto=".2f", aspect="auto",
                    color_continuous_scale="RdBu_r", range_color=[-1, 1],
                    title="Pearson Correlation Heatmap")
    fig.update_layout(height=600)
    fig.show()

    # Strong correlations
    strong = []
    for i in range(len(corr.columns)):
        for j in range(i+1, len(corr.columns)):
            r = corr.iloc[i, j]
            if abs(r) > 0.7:
                strong.append({'Var 1': corr.columns[i], 'Var 2': corr.columns[j], 'r': round(r, 3)})

    if strong:
        print("🔗 Strong Correlations (|r| > 0.7):")
        display(pd.DataFrame(strong))
    else:
        print("No strong correlations found.")
"""))

    # ═══════════════ SECTION 5: VISUALISATION ═══════════════
    if include_visualisation:
        cells.append(_md_cell("""## 5. Visualisation & EDA

### Chart Selection Guide
| Question | Chart Type | When to Use |
|----------|-----------|-------------|
| Distribution of one variable | Histogram | Continuous data |
| Category counts | Bar chart | Categorical data |
| Relationship between two variables | Scatter plot | Two numeric variables |
| Composition | Pie/Donut chart | Parts of a whole |
| Trends over time | Line chart | Time-series data |
| Distribution comparison | Box plot | Comparing groups |
"""))

        cells.append(_code_cell("""# ═══════════════ Distribution Plots ═══════════════
num_cols = df_cleaned.select_dtypes(include=[np.number]).columns

# Histogram for top numeric columns
fig, axes = plt.subplots(min(3, len(num_cols)), 2, figsize=(14, 4*min(3, len(num_cols))))
axes = axes.flatten() if len(num_cols) > 1 else [axes]

for i, col in enumerate(num_cols[:6]):
    ax = axes[i]
    df_cleaned[col].hist(bins=30, ax=ax, color='#6C63FF', alpha=0.7, edgecolor='white')
    ax.set_title(f'Distribution of {col}', fontweight='bold')
    ax.set_xlabel(col)
    ax.set_ylabel('Count')

plt.tight_layout()
plt.show()
"""))

        cells.append(_code_cell("""# ═══════════════ Categorical Analysis ═══════════════
cat_cols = df_cleaned.select_dtypes(include=['object', 'string', 'category']).columns

for col in cat_cols[:3]:  # Top 3 categorical columns
    counts = df_cleaned[col].value_counts().head(15)
    fig = px.bar(x=counts.index, y=counts.values,
                title=f'Distribution of {col}',
                labels={'x': col, 'y': 'Count'},
                color=counts.values, color_continuous_scale='Viridis')
    fig.show()
"""))

    # ═══════════════ SECTION 6: FEATURE ENGINEERING ═══════════════
    cells.append(_md_cell("""## 6. Feature Engineering

**What is Feature Engineering?** Creating new features from existing data to improve model performance.
This is often the most impactful step in the ML pipeline.

### Common Techniques
| Technique | Purpose | Example |
|-----------|---------|---------|
| One-Hot Encoding | Convert categories to numbers | State → State_Lagos, State_Abuja |
| Standard Scaling | Normalise feature ranges | Income 50000→0.5, 100000→1.0 |
| Label Encoding | Ordinal categories to numbers | Low→0, Medium→1, High→2 |
| PCA | Dimensionality reduction | 20 features → 5 components |
"""))

        cells.append(_code_cell("""# ═══════════════ Feature Engineering Pipeline ═══════════════
from sklearn.preprocessing import StandardScaler, LabelEncoder

# Separate features and target (modify target_col)
# target_col = 'your_target_column'  # ← Uncomment and set your target
# X = df_cleaned.drop(columns=[target_col])
# y = df_cleaned[target_col]

# Encode categorical features
df_encoded = df_cleaned.copy()
le_dict = {}  # Store label encoders for later use

cat_cols = df_encoded.select_dtypes(include=['object', 'string', 'category']).columns
for col in cat_cols:
    le = LabelEncoder()
    df_encoded[col + '_encoded'] = le.fit_transform(df_encoded[col].astype(str))
    le_dict[col] = le
    print(f"🔤 {col}: {len(le.classes_)} categories encoded")

# Scale numeric features
num_cols = df_encoded.select_dtypes(include=[np.number]).columns
scaler = StandardScaler()
df_scaled = df_encoded.copy()
df_scaled[num_cols] = scaler.fit_transform(df_encoded[num_cols])
print(f"\\n📐 {len(num_cols)} numeric features scaled (StandardScaler)")

df_scaled.head()
"""))

    # ═══════════════ SECTION 7: ML PIPELINE ═══════════════
    if include_ml:
        cells.append(_md_cell("""## 7. Machine Learning Pipeline

### Model Selection Guide
| Algorithm | Best For | Key Parameter |
|-----------|----------|---------------|
| Logistic Regression | Binary classification baseline | C (regularisation) |
| Random Forest | General-purpose, robust | n_estimators, max_depth |
| Gradient Boosting | High accuracy | n_estimators, learning_rate |
| SVM | Small-medium datasets | C, kernel |

> **⚠️ Important:** The code below is a template. You must set `target_col` to your actual target variable.
"""))

        cells.append(_code_cell("""# ═══════════════ ML Pipeline Template ═══════════════
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score, f1_score, classification_report,
    confusion_matrix, roc_auc_score
)

# ─── CONFIGURE YOUR TARGET ───
# target_col = 'your_target_column'  # ← SET YOUR TARGET COLUMN
# X = df_scaled.drop(columns=[target_col, *cat_cols.tolist()])  # Drop original cat cols
# y = df_scaled[target_col]

# ─── UNCOMMENT THE CODE BELOW AFTER SETTING TARGET_COL ───
"""
# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y if len(y.unique()) <= 20 else None
)

# Define models
models = {
    'Logistic Regression': LogisticRegression(max_iter=1000, random_state=42),
    'Random Forest': RandomForestClassifier(n_estimators=100, random_state=42),
    'Gradient Boosting': GradientBoostingClassifier(n_estimators=100, random_state=42),
}

# Train and evaluate each model
results = []
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred, average='weighted')

    results.append({'Model': name, 'Accuracy': acc, 'F1 Score': f1})

    print(f"\\n{'='*40}")
    print(f"📊 {name}")
    print(f"{'='*40}")
    print(classification_report(y_test, y_pred))

# Model comparison
results_df = pd.DataFrame(results).sort_values('F1 Score', ascending=False)
print("\\n🏆 Model Comparison:")
display(results_df)
"""
print("⚠️ Set target_col and uncomment the ML code to run the pipeline.")
"""))

    # ═══════════════ SECTION 8: MODEL EVALUATION ═══════════════
    cells.append(_md_cell("""## 8. Model Evaluation & Explainability

After training models, evaluate them beyond accuracy:
- **Confusion Matrix**: Where does the model make mistakes?
- **Feature Importance**: Which features drive predictions?
- **Cross-validation**: Is the model stable across data splits?
"""))

        cells.append(_code_cell("""# ═══════════════ Feature Importance (Tree Models) ═══════════════
# Feature importance analysis using a simple Random Forest
# Replace with your actual feature names and target

"""
# After training a Random Forest model:
# importances = rf_model.feature_importances_
# feat_importance = pd.DataFrame({
#     'Feature': X.columns,
#     'Importance': importances
# }).sort_values('Importance', ascending=False)

# fig = px.bar(feat_importance.head(15), x='Importance', y='Feature',
#             orientation='h', title='Top 15 Features (Random Forest)')
# fig.show()
"""

print("⚠️ Uncomment after training a model.")
"""))

    # ═══════════════ SECTION 9: EXPORT ═══════════════
    if include_deployment:
        cells.append(_md_cell("""## 9. Export & Deployment

### Deployment Options (Free!)
| Platform | Cost | Setup Time | URL Format |
|----------|------|------------|------------|
| Streamlit Cloud | Free | 5 min | `app-name.streamlit.app` |
| Hugging Face Spaces | Free | 10 min | `huggingface.co/spaces/name` |
| Render | Free tier | 10 min | `app-name.onrender.com` |

---

### 📋 Deployment Checklist
- [ ] Requirements.txt is complete
- [ ] No hardcoded paths or API keys
- [ ] Error handling for user inputs
- [ ] Mobile-responsive layout
- [ ] Test with multiple datasets
"""))

        cells.append(_code_cell("""# ═══════════════ Export Cleaned Data ═══════════════
# Save cleaned dataset
df_cleaned.to_csv('cleaned_data.csv', index=False)
print("✅ Saved: cleaned_data.csv")

# Save scaled dataset
df_scaled.to_csv('scaled_data.csv', index=False)
print("✅ Saved: scaled_data.csv")

# Export as Parquet (more efficient for large datasets)
df_cleaned.to_parquet('cleaned_data.parquet', index=False)
print("✅ Saved: cleaned_data.parquet")

print("\\n📁 All exports complete!")
"""))

    # ═══════════════ FOOTER ═══════════════
    cells.append(_md_cell(f"""---

## 📋 Summary & Next Steps

This notebook covered the complete data science workflow:
1. ✅ Data Loading & Exploration
2. ✅ Data Cleaning & Preprocessing
3. ✅ Statistical Analysis
4. ✅ Visualisation & EDA
5. ✅ Feature Engineering
6. ✅ Machine Learning Pipeline
7. ✅ Export & Deployment

### Next Steps
- Fine-tune model hyperparameters
- Build a Streamlit app for interactive predictions
- Set up monitoring for data drift
- Deploy to Streamlit Community Cloud

---

*Generated by **DataScience Flow v9.5** — Part of HMG Academy Ecosystem*

*HMG Academy — Subsidiary of HMG Concepts (est. 2015)*

**Builder:** Adewale Samson Adeagbo | Data Scientist | EdTech Builder | AI-Augmented Solutions Developer

🔗 [Portfolio](https://cssadewale.pages.dev/) | [HMG Concepts](https://hmgconcepts.pages.dev/) | [HMG Academy](https://hmgacademy.pages.dev/) | [HMG Technologies](https://hmgtechnologies.pages.dev/) | [HMG Media](https://hmgmedia.pages.dev/) | [HMG Gospel](https://hmggospel.pages.dev/)

📧 adeagboadewalesamson@gmail.com | 📞 +234 810 086 6322 | 📍 Lagos, Nigeria

---

> **© HMG Concepts (est. 2015) — All Rights Reserved**
> This notebook is generated under HMG Academy license. Not for resale.
> Unauthorized redistribution is prohibited.
"""))

    # Build the notebook JSON
    notebook = {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3 (ipykernel)",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "codemirror_mode": {"name": "ipython", "version": 3},
                "file_extension": ".py",
                "mimetype": "text/x-python",
                "name": "python",
                "nbconvert_exporter": "python",
                "pygments_lexer": "ipython3",
                "version": "3.11.0"
            },
            "datascienceflow": {
                "version": "v9.5",
                "organisation": "HMG Academy — Subsidiary of HMG Concepts",
                "builder": "Adewale Samson Adeagbo",
                "generated_at": datetime.now().isoformat(),
                "website": "https://hmgacademy.pages.dev",
                "portfolio": "https://cssadewale.pages.dev",
                "license": "Generated under HMG Academy license — not for resale",
            }
        },
        "cells": cells
    }

    return json.dumps(notebook, indent=1, ensure_ascii=False)


def generate_quick_notebook(code_cells: list, title: str = "Quick Analysis") -> str:
    """
    Generate a simpler notebook from a list of code strings.
    Used for quick exports from the Notebook Playground.
    """
    cells = []

    # Title
    cells.append(_md_cell(f"""# {title}

*Generated by DataScience Flow v9.5 | HMG Academy — HMG Concepts*

**Builder:** Adewale Samson Adeagbo | **Date:** {datetime.now().strftime("%Y-%m-%d %H:%M")}
"""))

    # Code cells
    for i, code in enumerate(code_cells):
        cells.append(_code_cell(code))

    # Footer
    cells.append(_md_cell("""---

*Generated by DataScience Flow v9.5 | HMG Academy — Subsidiary of HMG Concepts (est. 2015)*

*Unauthorized redistribution is prohibited. © HMG Concepts — All Rights Reserved.*
"""))

    notebook = {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.11.0"},
            "datascienceflow": {
                "version": "v9.5",
                "organisation": "HMG Academy — Subsidiary of HMG Concepts",
                "builder": "Adewale Samson Adeagbo",
                "generated_at": datetime.now().isoformat(),
            }
        },
        "cells": cells
    }

    return json.dumps(notebook, indent=1, ensure_ascii=False)
