"""
Module 50: API Doc Generator — DataScience Flow v9.5
Part of HMG Academy Ecosystem — Subsidiary of HMG Concepts
"""
import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from subscription import init_subscription_state, TIERS, tier_badge_html, get_tier_info, local_save_subscription
from security import (
    init_secure_session, verify_subscription_integrity,
    authenticate_subscription, check_rate_limit, check_export_limit,
    validate_upload, sanitise_string, sanitise_email,
    log_action, check_session_timeout,
    watermark_dataframe, BRAND_WATERMARK, BRAND_FOOTER,
)

# ═══ Security & Session Verification ═══
init_secure_session()
if not st.session_state.get("sub_authenticated"):
    st.warning("⚠️ Subscription required. Start your free trial from the Home page.")
    st.stop()
if not verify_subscription_integrity():
    st.error("🔒 Session integrity check failed. Please re-authenticate.")
    st.stop()
if check_session_timeout():
    st.warning("⏰ Session expired. Please re-authenticate.")
    st.stop()
check_rate_limit()

if not verify_subscription_integrity():
    st.error("🔒 Session integrity check failed. Please re-authenticate.")
    st.stop()
if check_session_timeout():
    st.warning("⏰ Session expired. Please re-authenticate.")
    st.stop()
check_rate_limit()



st.set_page_config(page_title="API Doc Generator | DataScience Flow", page_icon="📡", layout="wide")
st.markdown('<div style="font-size:2.2rem;font-weight:800;background:linear-gradient(135deg,#6C63FF,#00D9A7);-webkit-background-clip:text;-webkit-text-fill-color:transparent;">📡 API DOC GENERATOR</div>', unsafe_allow_html=True)
st.markdown("""**🧠 What this module does:** Auto-generate OpenAPI 3.0 specification from Data Dictionary. Define endpoints (GET/POST/PUT/DELETE) with response/request columns. Schema properties auto-populated with types, descriptions, examples. cURL command examples. Markdown API documentation.

**🎯 Why you need it:** When your data pipeline needs an API, this generates professional API documentation automatically from your data dictionary.

**📖 How to use it:** Review data dictionary → define endpoints → generate OpenAPI spec → download as JSON or Markdown.""")
if st.session_state.get("df") is None:
    st.warning("⚠️ No dataset loaded.")
    st.stop()
dfc = st.session_state["df_cleaned"]


st.markdown("### 📡 API Documentation Generator")
st.caption("Generate OpenAPI 3.0 specification from your Data Dictionary.")

dd = st.session_state.get("data_dictionary", {})
if not dd:
    st.warning("⚠️ Please build your Data Dictionary first (Home page → Data Dictionary tab).")
    st.stop()

st.markdown("#### API Endpoints")
endpoints = st.multiselect("Endpoints to document", ["GET /data", "POST /data", "GET /data/{id}", "PUT /data/{id}", "DELETE /data/{id}"],
    default=["GET /data", "GET /data/{id}"])

api_title = st.text_input("API Title", f"DataFlow API — {st.session_state.get('filename', 'Dataset')}")
api_version = st.text_input("API Version", "1.0.0")

if st.button("📡 Generate API Documentation"):
    # Build OpenAPI spec
    properties = {}
    for col, info in dd.items():
        prop = {"description": info.get("description", ""), "example": info.get("unit", "")}
        col_dtype = str(dfc[col].dtype)
        if "int" in col_dtype: prop["type"] = "integer"
        elif "float" in col_dtype: prop["type"] = "number"
        elif "bool" in col_dtype: prop["type"] = "boolean"
        else: prop["type"] = "string"
        properties[col] = prop
    
    spec = {
        "openapi": "3.0.3",
        "info": {"title": api_title, "version": api_version, "description": f"Auto-generated by DataScience Flow Suite v7.0 | HMG Concepts"},
        "paths": {}
    }
    
    if "GET /data" in endpoints:
        spec["paths"]["/data"] = {"get": {"summary": "List all records", "responses": {"200": {"description": "Success"}}}}
    
    st.markdown("### 📄 OpenAPI 3.0 Specification")
    st.json(spec)
    
    # cURL examples
    st.markdown("### 📋 cURL Examples")
    st.code(f"# List all records
curl -X GET https://api.example.com/data

# Get specific record
curl -X GET https://api.example.com/data/123", language="bash")
    
    # Markdown download
    md = f"# {api_title} v{api_version}

"
    md += "## Endpoints

"
    for ep in endpoints:
        md += f"### {ep}

"
        md += "**cURL:**
```bash
"
        if "GET" in ep:
            md += f"curl -X GET https://api.example.com{ep.split(' ',1)[1]}
"
        elif "POST" in ep:
            md += f"curl -X POST https://api.example.com{ep.split(' ',1)[1]} -H 'Content-Type: application/json' -d '{{}}'
"
        md += "```

"
    md += f"
## Schema Properties

| Column | Type | Description |
|--------|------|-------------|
"
    for col, prop in properties.items():
        md += f"| {col} | {prop.get('type','string')} | {prop.get('description','-')} |
"
    md += "
---
Generated by DataScience Flow Suite | HMG Concepts
"
    
    st.download_button("⬇️ Download API Docs (Markdown)", md.encode(), "api_documentation.md", "text/markdown")

# ═══════════════════════════════════════════════════════════════
# BRAND FOOTER — DataScience Flow v9.5 | HMG Academy
# ═══════════════════════════════════════════════════════════════
st.markdown("---")
st.markdown("""
<div style="text-align:center; padding:16px 0; font-size:0.82rem; color:#A0A8B8;">
<b>DataScience Flow</b> v9.5 — Part of <b>HMG Academy</b> Ecosystem — Subsidiary of <b>HMG Concepts</b> (est. 2015)<br>
Built by <b>Adewale Samson Adeagbo</b> | 🔒 Secured Platform | 🏗️ HMG Academy · HMG Technologies · HMG Media · HMG Gospel<br>
<a href="https://hmgacademy.pages.dev" style="color:#6C63FF;">hmgacademy.pages.dev</a> ·
<a href="https://hmgconcepts.pages.dev" style="color:#6C63FF;">hmgconcepts.pages.dev</a> ·
<a href="https://cssadewale.pages.dev" style="color:#6C63FF;">cssadewale.pages.dev</a>
</div>
""", unsafe_allow_html=True)
